# name: D:\Projects\MissingLectureOfMLClass\.env
channels:
  - conda-forge
dependencies:
  - python
  - ipywidgets
  - pandas
  - seaborn
  - ipywebrtc
  - scikit-learn
  - ipympl
  - voila
  - ipykernel
  - ffmpeg
  - tensorflow
  - tensorflow-datasets
# prefix: D:\Projects\MissingLectureOfMLClass\.env
